language: emacs-lisp
sudo: false

env:
  - EVM_EMACS=emacs-25.1-travis
  - EVM_EMACS=emacs-25.2-travis
  - EVM_EMACS=emacs-25.3-travis
  - EVM_EMACS=emacs-26.1-travis-linux-xenial
  - EVM_EMACS=emacs-26.2-travis-linux-xenial
  - EVM_EMACS=emacs-26.3-travis-linux-xenial
  - EVM_EMACS=emacs-git-snapshot-travis-linux-xenial

matrix:
  fast_finish: true
  allow_failures:
    - env: EVM_EMACS=emacs-git-snapshot-travis-linux-xenial

before_install:
  - |
    if ! git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qvE '(.md)|(.png)|(.pdf)|(.html)|^(LICENSE)|^(docs)'; then
      echo "Not running CI since only docs were changed."
      exit
    fi

install:
  - mv -f ../.emacs.d ~/.emacs.d

  - export PATH="/home/travis/.evm/bin:$PATH"
  - export PATH="/home/travis/.cask/bin:$PATH"
  - git clone https://github.com/rejeep/evm.git /home/travis/.evm
  - evm config path /tmp
  - evm install $EVM_EMACS --use --skip
  - curl -fsSkL https://raw.github.com/cask/cask/master/go | python

  - echo "Importing elpa key..."
  - EMACS_GNUPGHOME=$HOME/.emacs.d/elpa/gnupg
  - mkdir -p "$EMACS_GNUPGHOME"
  - chmod 700 "$EMACS_GNUPGHOME"
  - wget 'https://git.savannah.gnu.org/cgit/emacs.git/plain/etc/package-keyring.gpg'
  - gpg --homedir "$EMACS_GNUPGHOME" --import package-keyring.gpg

script:
  - echo "Attempting startup..."
  - ${EMACS:=emacs} -nw --batch --eval
    '(let ((debug-on-error (>= emacs-major-version 26))
           (package-check-signature nil)
           (url-show-status nil)
           (early-init-file (locate-user-emacs-file "early-init.el"))
           (user-init-file (locate-user-emacs-file "init.el")))
    (when (>= emacs-major-version 27)
      (load early-init-file))
    (load user-init-file)
    (run-hooks (quote after-init-hook))
    (run-hooks (quote emacs-startup-hook))
    (run-hooks (quote window-setup-hook)))'

after_success:
  - echo "Startup successful"
